### ISSUE TITLE
Contact info?

### ISSUE THREAD

**Issue by bohdloss** [gtsiam/dfdi#1]
Hey gtsiam, sorry for opening a GitHub issue but I can't find any other way to contact you. I was curious if you would be willing to transfer to me ownership of your crate "ender" since you stopped developing it from what I can tell, but would make a cool name for a project I'm publishing! :)
Of course, I understand if you don't want to.
Regardless, feel free to contact me at: antonio.marangon2@gmail.com
Thanks!

**Comment by gtsiam** [comment]
Normally I'd say yes, but now I'm tempted to actually try and finish my generics-based serializer - Which funnily enough I'd called deser before the deser crate got published (not by me) - that mildly demotivated me ngl

I'd run into HRTB issues before GAT stabilized, so I'd like to take another crack at it before I hand over the name. I'm not at home right now so I cant work on it, but I'll give it a shot and shoot you an email within the month (my email is gtsiam@windowslive.com, you can see it on all my commits)

**Comment by bohdloss** [comment]
That's fair, do keep me updated tho!
